## Remember that the solutions need to be saved int variable provided.

In [1]:
# Import the needed libraries - only numpy here 
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [35]:
sol1 = np.random.rand(10,10)
print("The Size of the Array is: ",sol1.shape)
max_sol = sol1.max()
print("The Maximum is: ",max_sol)
min_sol = sol1.min()
print("The Minimum is: ",min_sol)

The Size of the Array is:  (10, 10)
The Maximum is:  0.9740525918440549
The Minimum is:  0.008377693472429337


In [3]:
assert sol1.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [4]:
sol2=np.ones((10,10))
sol2[1:-1,1:-1]=0
print(sol2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [34]:
sol3 = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print("Dates in July 2016 (YYYY-MM-DD): \n")
print(sol3)

Dates in July 2016 (YYYY-MM-DD): 

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [7]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [8]:
sol41 = np.random.normal(loc=0.0, scale=1.0, size=(10,10))
sol41 = np.array(sol41)
#print ("Normal:\n",sol41)
sol42 = np.random.uniform(low=-1, high=1, size=(10,10))
#print("Random:\n",sol42)
comparisson = (sol41 == sol42)
print("Comparision of Values in Normal and Uniform Distributed Arrays: \n",sol41 == sol42)

Comparision of Values in Normal and Uniform Distributed Arrays: 
 [[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


In [9]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [36]:
sol5 = np.array([[1,2,3],[4,5,6]])
print("Array before Swap:\n",sol5)
sol5[[0,1]]=sol5[[1,0]]
print("Array after Swap:\n ",sol5)


Array before Swap:
 [[1 2 3]
 [4 5 6]]
Array after Swap:
  [[4 5 6]
 [1 2 3]]


In [11]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [43]:
arr =([1,2,3,4,5,6,7,8,9,10])
print("Array of elements given:\n",arr)
n=len(arr)
print("Number of elements: ",n)
# A "Sliding Window" contains elements from first to  incrementing last.
# The values of these elements are incrementally summarized using the cumsum-method.
# These increasing sums are divided by the total number of elements, as an average.
window_sum_until_element = np.cumsum(arr)
sol6 = window_sum_until_element/n
print("Sliding Window Averages (sol6):\n", sol6)

Array of elements given:
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Number of elements:  10
Sliding Window Averages (sol6):
 [0.1 0.3 0.6 1.  1.5 2.1 2.8 3.6 4.5 5.5]


In [13]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5