
# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [215]:
import numpy as np
import pandas as pd

In [216]:
def add_vectors(u, v):
    u = np.array(u)
    v = np.array(v)
    result = u + v
    print(result)
    return result

In [217]:
#test OK
add_vectors([1, 0], [1, 1])
add_vectors([1, 2], [1, 4])
add_vectors([1, 2, 1], [1, 4, 3])
add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
a = [1, 2, 3]
b = [1, 1, 1]
add_vectors(a, b)
a = [1, 2, 3]
b = [1, 1, 1]
add_vectors(a, b)
"""
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
"""
pass

[2 1]
[2 6]
[2 6 4]
[13 -4 13  5]
[2 3 4]
[2 3 4]


Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [218]:
def scalar_mult(s, v):
    v = np.array(v)
    result = v*s
    print(result)
    return(result)

In [219]:
# test OK
scalar_mult(3, [1, 0, -1])
scalar_mult(7, [3, 0, 5, 11, 2])
a = [1, 2, 3]
scalar_mult(4, a)
"""   >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
"""
pass

[ 3  0 -3]
[21  0 35 77 14]
[ 4  8 12]


Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [220]:
def dot_product(u, v):
    u = np.array(u)
    v = np.array(v)
    result = np.dot(u, v)
    print(result)
    return result
print("Test:")
dot_product([1, 1], [1, 1])
dot_product([1, 2], [1, 4])
dot_product([1, 2, 1], [1, 4, 3])
dot_product([2, 0, -1, 1], [1, 5, 2, 0])

Test:
2
9
12
0


0

In [221]:
    """ dot product info
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
    pass

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [222]:
def copy_matrix(matrix):
    matrix = matrix
    other_matrix = np.copy(matrix)
    matrix
    other_matrix = other_matrix
    print(matrix)
    print(other_matrix)
    return other_matrix
#test
copy_matrix([[1, 2], [3, 4]])
copy_matrix([[1, 2, 3], [4, 5, 6]])
copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])

# test OK , checked! Remark: matrix and copy_matrix change independently
# dont did the case supplied, but ists fullfilled
"""
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
"""
pass

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[1, 2], [3, 4], [5, 6], [7, 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [223]:
#def add_row(matrix, row)- long version:

matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
matrix = np.array(matrix)
size_m = matrix.size
rows_m = len(matrix)
columns_m = int(size_m/rows_m)
print("Size of the Matrix:",size_m)
print("Rows of the Matrix",rows_m)
print("Columns of the Matrix:", columns_m)
new_row = np.zeros(columns_m)
new_row_array = np.array(new_row)
print("New row to be added:",new_row_array)
result = np.vstack([matrix, new_row])
#print(matrix)
print(result)
print("happy ")

Size of the Matrix: 8
Rows of the Matrix 4
Columns of the Matrix: 2
New row to be added: [0. 0.]
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]
 [0. 0.]]
happy 


In [224]:
#Add column, names CORRECTed
matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
matrix = np.array(matrix)
size_m = matrix.size
rows_m = len(matrix)
columns_m = int(size_m/rows_m)
print("Size of the Matrix:",size_m)
print("Rows of the Matrix",rows_m)
print("Columns of the Matrix:", columns_m)
new_row = np.zeros(rows_m)
new_row_array = np.array(new_row)
print("New column to be added:",new_row_array)
result = np.column_stack([matrix, new_row])
#print(matrix)
print(result)
print("happy ")

Size of the Matrix: 8
Rows of the Matrix 4
Columns of the Matrix: 2
New column to be added: [0. 0. 0. 0.]
[[1. 2. 0.]
 [3. 4. 0.]
 [5. 6. 0.]
 [7. 8. 0.]]
happy 


In [225]:
# short Add one column of  zeros - at the end
matrix_a = [[1, 2], [3, 4], [5, 6], [7, 8]]
def add_column(matrix):
    matrix = np.array(matrix)
    new_row = np.zeros(len(matrix))
    result = np.column_stack([matrix, new_row])
return result
#test OK
print("A last column of zeros was added:")
print(add_column(matrix_a))
pass

SyntaxError: 'return' outside function (<ipython-input-225-1b3b1e3afa92>, line 7)

In [226]:
#Add column, names crazy, please never use, just for demo
matrix = [[1, 2], [3, 4], [5, 6], [7, 8]]
matrix = np.array(matrix)
size_m = matrix.size
rows_m = len(matrix)
columns_m = int(size_m/rows_m)
print("Size of the Matrix:",size_m)
print("Rows of the Matrix",rows_m)
print("Columns of the Matrix:", columns_m)
new_column = np.zeros(rows_m)
new_column_array = np.array(new_column)
print("New column to be added:",new_column_array)
result = np.column_stack([matrix, new_row])
#print(matrix)
print(result)
print("so lala  ")

Size of the Matrix: 8
Rows of the Matrix 4
Columns of the Matrix: 2
New column to be added: [0. 0. 0. 0.]
[[1. 2. 0.]
 [3. 4. 0.]
 [5. 6. 0.]
 [7. 8. 0.]]
so lala  


Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [227]:
def add_matrices(u, v):
    return np.add(u, v)

pass


Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [228]:
def scalar_mult(s, m):
    result = np.dot(s, m)
    print(result)
    return(result)

#test
a = [[1, 2], [3, 4]]
scalar_mult(3, a)

print("Result expected:[[3, 6], [9, 12]] ")

"""
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
"""
pass

[[ 3  6]
 [ 9 12]]
Result expected:[[3, 6], [9, 12]] 


Write functions row_times_column and matrix_mult:

In [229]:
### NOT THE EXPECTED SOLUTION

def row_times_column(m1, row, m2, column):
    result= np.dot(m1[row],m2[column]) 
#index of row = index 0  index of column = 1 
    print(m1,row,m2,column)
    print(result)
    return(result)
#test
row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)

print("Result expected 19")
print("not happy!")

"""
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
"""
pass

[[1, 2], [3, 4]] 0 [[5, 6], [7, 8]] 0
17
Result expected 19
not happy!


In [230]:
def matrix_mult(m1, m2):
    return np.matmul((np.array(m1)), np.array(m2))

print(matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]]))
print("Result expected: [[19, 22], [43, 50]]")
print(matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]]))
print("Result expcted: [[31, 19], [85, 55]])")
print(matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]]))
print("Result expected: [[39, 54, 69], [13, 23, 33], [14, 19, 24]])")
# print(matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]]))



"""
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
"""
pass

[[19 22]
 [43 50]]
Result expected: [[19, 22], [43, 50]]
[[31 19]
 [85 55]]
Result expcted: [[31, 19], [85, 55]])
[[39 54 69]
 [13 23 33]
 [14 19 24]]
Result expected: [[39, 54, 69], [13, 23, 33], [14, 19, 24]])


Write a function transpose that takes a matrix as an argument and returns is transpose:

In [231]:
def transpose(m):
    return np.array(m).T

pass


###The end