## Linear Algebra Quiz #2

![title](./img/2_1.jpeg)

We strongly suggest working with numpy :)

In [174]:
import numpy as np

![title](./img/2_2.png)
- Which vectors below define a plane spanned by a linear combination?

In [209]:
#def plane(a,b,c):
#returns false if the vectors do define a plane and returns which are those vectors if true
a= np.array([1,2,3])
b= np.array([4,4,4])
c= np.array([8,8,8])

#def plane(a,b,c)
#Ax=λx heißt Eigenvektor der Matrix A zum Eigenwert λ.
matrix = np.stack((a,b,c))
print("Matrix:\n", matrix)
eigenwerte_lambda, eigen_vector = np.linalg.eig(matrix)
print("Eigenwerte Lambda:\n ",eigenwerte_lambda)
print("Eigenvektor: ",eigen_vector)

#check if one Lambda is zero: alltogether: 3D falls to 2D
#for i in range(2):
for i in range(3):
    if abs(eigenwerte_lambda[i]) < 10e-15:
# Setting done for "nearly zero" is to be calculated properly :
            print("Dependent Vectors found")
    else:
        pass
print("search for dependent vectors finished")

Matrix:
 [[1 2 3]
 [4 4 4]
 [8 8 8]]
Eigenwerte Lambda:
  [ 1.43898669e+01 -1.38986692e+00 -8.20803901e-16]
Eigenvektor:  [[ 0.25813938  0.83154279  0.40824829]
 [ 0.43205649 -0.24840958 -0.81649658]
 [ 0.86411298 -0.49681915  0.40824829]]
Dependent Vectors found
search for dependent vectors finished


In [176]:
# CHECK FOR LINEAR INDEPENDENCY OF 3 VECTORS
v1= np.array([1,2,3])
v2= np.array([2,2,2])
v3= np.array([8,8,8])

#Check vectors angles x,y-> if parallels found ->result is True
v1_theta = np.arctan(v1[0]/v1[1])
v2_theta = np.arctan(v2[0]/v2[1])
v3_theta = np.arctan(v3[0]/v3[1])
result_1 = (v1_theta == v2_theta) or (v2_theta == v3_theta) 

#Check next plane y,z - enough to check 2 planes in 3D
v1_theta = np.arctan(v1[1]/v1[2])
v2_theta = np.arctan(v2[1]/v2[2])
v3_theta = np.arctan(v3[1]/v3[2])
result_2 = (v1_theta == v2_theta) or (v2_theta == v3_theta) 


if (result_1 == True) or (result_2 == True): 
    print("The vectors are not independent!")    
else:
    print ("Vectors define a 3D-world")



The vectors are not independent!


![title](./img/2_3.png)
- What is the solution for a and b?

In [ ]:
# do you need a function for this? What is the most efficient way to solve it?

![title](./img/2_4.png)
- What is the solution for a and b?

In [ ]:
# Idem. Do you need a function for this? What is the most efficient way to solve it?